### ISSUE TITLE
Make the docker images publicly available

### ISSUE THREAD

**Issue by exaexa** [mff-cuni-cz/cuni-thesis-validator#3]
Unfortunately it seems a bit more config clicking is needed, to make the "private" badge from here https://github.com/mff-cuni-cz/cuni-thesis-validator/pkgs/container/cuni-thesis-validator go disappear. I think the setting can be found somewhere in organization settings under "publishable packages" or so.

Refs: https://github.com/mff-cuni-cz/cuni-thesis-validator/pull/2#issuecomment-1123939674

cc @jjonescz

**Comment by exaexa** [comment]
(...likely somewhere around here https://github.com/orgs/mff-cuni-cz/packages)

**Comment by vitkabele** [comment]
Should be done now. Could you please check with your workflow?

**Comment by exaexa** [comment]
b e a u t i f u l
works perfectly as seen here https://github.com/exaexa/better-mff-thesis/runs/6402796425 , thanks a lot!
