### ISSUE TITLE
Error relocating `/__e/node16_alpine/bin/node`: getentropy: symbol not found

### ISSUE THREAD

**Issue by exaexa** [mff-cuni-cz/cuni-thesis-validator#4]
I got the issue title message right here after pulling the changes from my repo:

https://github.com/mff-cuni-cz/better-thesis/actions/runs/4365797418/jobs/7635508329#step:3:5

No real idea what that means, but looks to me like either the action got broken or the docker image is no longer a sufficiently happy place to support it.

**Comment by vitkabele** [comment]
Hello, could you please re-run your workflow with the updated container and confirm whether it was fixed by the obsolete image?

**Comment by exaexa** [comment]
all seems good (https://github.com/mff-cuni-cz/better-thesis/actions/runs/4365797418/jobs/7649377619#step:3:5), thanks a lot!
